### ISSUE TITLE
Front-end: Members Page for Admin View

### ISSUE THREAD

**Issue by thejamielin** [Code-4-Community/outstanding-life#60]
# Purpose
Implement UI for Admins to view and download a list of all current members

# Description
Implement UI for table of all members and download a list of members by referencing the [Izzy's designs on Figma](https://www.figma.com/file/uKPcL5G1ZwVC3SGuacJco6/Outstanding-Life?node-id=1615%3A10586)
- [ ] Header
- [ ] Download
- [ ] Table view of members - can use mock data for now

# Acceptance Criteria
- [ ] Cypress tests to see if all components exist

**Comment by adriannaliu** [comment]
closing bc we no longer need to implement this functionality.
