### ISSUE TITLE
Back-end/Misc: Change outstandinglife to use HTTPS

### ISSUE THREAD

**Issue by jessicasu77** [Code-4-Community/outstanding-life#67]
Right now, http://outstandinglife.org exists but we want to change this to https://outstandinglife.org because in order for Amazon Cognito redirect to our website upon SIGN IN, our website has to be in HTTPS

Full conversation here: https://c4cneuteams.slack.com/archives/C02N2ULMVNJ/p1662823104370849

Acceptance Criteria:
- [ ] Change http://outstandinglife.org to https://outstandinglife.org
- [ ] Change the Callback URLS of the User Pool App Client settings to use the new URLS (as specified in the slack post)

Notes:
- need an HTTPS certificate
- extended domain validation = the server is who we think they are
- validation SSL
- We use amplify to serve
- Need shell access to run ACME client

TO DO:
- ask Jamie to see our tech stack in full and how it works
- Make a cron job (job schedular on linux)

**Comment by thejamielin** [comment]
Deprecated ticket because Amplify provides us with the https://
